services:
    fgms_special_offers.to_https:
        class: Fgms\EmailInquiriesBundle\EventListener\ToHttpsListener
        arguments: ["@router"]
        tags:
            -   { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
