<?php

namespace Fgms\EmailInquiriesBundle\Repository;

/**
 * StoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Obtains the Store entity with a certain name.
	 *
	 * @param string $name
	 *
	 * @return Store|null
	 */
	public function getByName($name)
	{
		$qb = $this->createQueryBuilder('s');
		$qb->andWhere($qb->expr()->eq('s.name',':name'))
			->setParameter('name',$name);
		$q = $qb->getQuery();
		$arr = $q->getResult();
		if (count($arr) !== 1) return null;
		return $arr[0];
	}
}
